{"name": "Register with duplicate values", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'method'\n", "trace": "  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"features\\environment.py\", line 26, in after_step\n    allure.attach(context.driver.get_screenshot_as_png,\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n                  name=\"failed_screenshot\",\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n                  attachment_type=AttachmentType.PNG)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_behave\\listener.py\", line 171, in attach_data\n    self.logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^\n"}, "steps": [{"name": "Given Navigate to register page", "status": "passed", "start": 1737117476524, "stop": 1737117477272}, {"name": "When Enter details into all field expect email fields", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'method'\n", "trace": "  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"features\\environment.py\", line 26, in after_step\n    allure.attach(context.driver.get_screenshot_as_png,\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n                  name=\"failed_screenshot\",\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n                  attachment_type=AttachmentType.PNG)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_behave\\listener.py\", line 171, in attach_data\n    self.logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^\n"}, "attachments": [{"name": "failed_screenshot", "source": "bb080735-92f7-4f1d-bff3-900415fffcce-attachment.png", "type": "image/png"}], "start": 1737117477273, "stop": 1737117477281}, {"name": "And Enter details into existing email field", "status": "skipped", "start": 1737117479528, "stop": 1737117479528}, {"name": "And CLick on continue button", "status": "skipped", "start": 1737117479528, "stop": 1737117479528}, {"name": "Then Proper error message should displayed in duplicate email filed", "status": "skipped", "start": 1737117479528, "stop": 1737117479528}], "start": 1737117473478, "stop": 1737117479528, "uuid": "41cd439b-3abc-4540-aa39-481aba3e46ad", "historyId": "4e75f17c5b3b09a4354c686cd0e01eba", "fullName": "To test the register functionalities: Register with duplicate values", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "To test the register functionalities"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}