{"name": "Register with mandatory fields", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'method'\n", "trace": "  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"features\\environment.py\", line 26, in after_step\n    allure.attach(context.driver.get_screenshot_as_png,\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n                  name=\"failed_screenshot\",\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n                  attachment_type=AttachmentType.PNG)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_behave\\listener.py\", line 171, in attach_data\n    self.logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^\n"}, "steps": [{"name": "Given Navigate to register page", "status": "passed", "start": 1737117449122, "stop": 1737117449962}, {"name": "When Enter details into mandatory field", "status": "passed", "attachments": [{"name": ".table", "source": "aaf30034-df1b-4092-b1ef-57a69c224933-attachment.csv", "type": "text/csv"}], "start": 1737117449963, "stop": 1737117460038}, {"name": "And CLick on continue button", "status": "passed", "start": 1737117460039, "stop": 1737117461069}, {"name": "Then Account should created", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'method'\n", "trace": "  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"features\\environment.py\", line 26, in after_step\n    allure.attach(context.driver.get_screenshot_as_png,\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n                  name=\"failed_screenshot\",\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n                  attachment_type=AttachmentType.PNG)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_behave\\listener.py\", line 171, in attach_data\n    self.logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL LATITUDE 7490\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n    ~~~~~~~~~~~~~~~~~~~^^^^^^\n"}, "attachments": [{"name": "failed_screenshot", "source": "7998b040-ccf8-475f-94d3-ef46af3e8391-attachment.png", "type": "image/png"}], "start": 1737117461069, "stop": 1737117461207}], "start": 1737117443725, "stop": 1737117463432, "uuid": "9d3ce77b-fce9-4ca1-972e-4c0b28998517", "historyId": "1a1400acebeb1fbd709545fffbfb32f2", "fullName": "To test the register functionalities: Register with mandatory fields", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "page"}, {"name": "feature", "value": "To test the register functionalities"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}